# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Rohan R. All rights reserved.

"""Lock file manager — generate, read, write, and sync envguard.lock."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from envguard.exceptions import LockFileError
from envguard.logging import get_logger
from envguard.models import LockFile, ResolvedPackage

try:
    import tomllib  # type: ignore[import-not-found]
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ImportError:
        tomllib = None  # type: ignore[assignment]

try:
    import tomli_w
except ImportError:
    tomli_w = None  # type: ignore[assignment]

logger = get_logger(__name__)

LOCK_FILENAME = "envguard.lock"


class LockManager:
    """Manage the envguard.lock file for a project.

    Args:
        project_dir: Root of the project.
    """

    def __init__(self, project_dir: Path) -> None:
        self.project_dir = Path(project_dir)
        self.lock_path = self.project_dir / LOCK_FILENAME

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def generate(
        self,
        requirements: list[str],
        python_requires: str | None = None,
        sources: list[str] | None = None,
        python_version: str | None = None,
    ) -> LockFile:
        """Resolve *requirements* and write envguard.lock.

        Args:
            requirements: PEP 508 requirement strings from the project.
            python_requires: Python version constraint (e.g. ``">=3.10"``).
            sources: Relative paths of source files used (for content hash).
            python_version: Target Python version string.

        Returns:
            The generated :class:`~envguard.models.LockFile`.
        """
        from envguard import __version__
        from envguard.resolver.pypi_resolver import PyPIResolver

        resolver = PyPIResolver(python_version=python_version)
        logger.info("Resolving %d requirements via PyPI...", len(requirements))
        packages = resolver.resolve(requirements)
        logger.info("Resolved %d packages", len(packages))

        content_hash = self._compute_content_hash(sources or [])

        lock = LockFile(
            envguard_version=__version__,
            python_requires=python_requires,
            content_hash=content_hash,
            packages=packages,
            sources=sources or [],
        )
        self.write(lock)
        return lock

    def update_package(
        self,
        package_name: str,
        requirements: list[str] | None = None,
    ) -> LockFile:
        """Re-resolve a single package and update the lock file.

        Args:
            package_name: Name of the package to update.
            requirements: Full requirements list to re-resolve.  If ``None``
                the existing lock's sources are used.
        """
        lock = self.read()

        if requirements is None:
            # Re-resolve just the one package at latest compatible version
            from envguard.resolver.pypi_resolver import PyPIResolver

            resolver = PyPIResolver()
            new_pkgs = resolver.resolve([package_name])
            # Update in lock
            updated = {p.normalized_name: p for p in lock.packages}
            for pkg in new_pkgs:
                updated[pkg.normalized_name] = pkg
            lock.packages = list(updated.values())
        else:
            lock = self.generate(requirements, lock.python_requires, lock.sources)

        self.write(lock)
        return lock

    # ------------------------------------------------------------------
    # Read / write
    # ------------------------------------------------------------------

    def write(self, lock: LockFile) -> None:
        """Serialise *lock* to TOML and write to ``envguard.lock``."""
        if tomli_w is None:
            raise LockFileError("tomli_w is required to write lock files: pip install tomli_w")

        data = self._to_toml_dict(lock)
        content = tomli_w.dumps(data)
        # Prepend a comment header (tomli_w doesn't support comments)
        header = (
            "# envguard.lock — generated by envguard\n"
            "# Do not edit manually. Regenerate with: envguard lock generate\n\n"
        )
        self.lock_path.write_text(header + content, encoding="utf-8")
        logger.info("Lock file written to %s", self.lock_path)

    def read(self) -> LockFile:
        """Read and parse the lock file.

        Raises:
            LockFileError: If the file does not exist or cannot be parsed.
        """
        if tomllib is None:
            raise LockFileError(
                "tomllib/tomli is required to read lock files. "
                "On Python < 3.11 install tomli: pip install tomli"
            )

        if not self.lock_path.exists():
            raise LockFileError(
                f"Lock file not found: {self.lock_path}. Run 'envguard lock generate' to create it."
            )

        try:
            with open(self.lock_path, "rb") as fh:
                data = tomllib.load(fh)  # type: ignore[union-attr]
        except Exception as exc:
            raise LockFileError(f"Failed to parse lock file: {exc}") from exc

        return self._from_toml_dict(data)

    def is_stale(self, sources: list[str] | None = None) -> bool:
        """Return ``True`` if the lock file is missing or its content hash is outdated."""
        if not self.lock_path.exists():
            return True
        try:
            lock = self.read()
        except LockFileError:
            return True
        current_hash = self._compute_content_hash(sources or lock.sources)
        return lock.content_hash != current_hash

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    def _to_toml_dict(self, lock: LockFile) -> dict[str, Any]:
        packages = []
        for pkg in sorted(lock.packages, key=lambda p: p.normalized_name):
            packages.append(
                {
                    "name": pkg.normalized_name,
                    "version": pkg.version,
                    "specifier": pkg.specifier,
                    "requires_python": pkg.requires_python or "",
                    "markers": pkg.markers or "",
                    "extras": list(pkg.extras),
                    "source": pkg.source,
                }
            )
        return {
            "metadata": {
                "envguard_version": lock.envguard_version,
                "generated_at": lock.generated_at,
                "python_requires": lock.python_requires or "",
                "content_hash": lock.content_hash,
                "sources": list(lock.sources),
            },
            "package": packages,
        }

    def _from_toml_dict(self, data: dict[str, Any]) -> LockFile:
        meta = data.get("metadata", {})
        packages = []
        for p in data.get("package", []):
            packages.append(
                ResolvedPackage(
                    name=p.get("name", ""),
                    version=p.get("version", ""),
                    normalized_name=p.get("name", ""),
                    specifier=p.get("specifier", ""),
                    requires_python=p.get("requires_python") or None,
                    markers=p.get("markers") or None,
                    extras=list(p.get("extras", [])),
                    source=p.get("source", "pypi"),
                )
            )
        return LockFile(
            envguard_version=meta.get("envguard_version", ""),
            generated_at=meta.get("generated_at", ""),
            python_requires=meta.get("python_requires") or None,
            content_hash=meta.get("content_hash", ""),
            packages=packages,
            sources=list(meta.get("sources", [])),
        )

    def _compute_content_hash(self, sources: list[str]) -> str:
        """SHA-256 of sorted, concatenated content of all source files."""
        hasher = hashlib.sha256()
        for rel_path in sorted(sources):
            full_path = self.project_dir / rel_path
            if full_path.exists():
                hasher.update(full_path.read_bytes())
        return "sha256:" + hasher.hexdigest()
